apiVersion: v1
kind: Service
metadata:
  annotations: kustomize.toolkit.fluxcd.io/prune: disabled
  creationTimestamp: null
  labels:
    app: vote
    tier: front
  name: vote
spec:
  ports:
  - name: "80"
    nodePort: 30301
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vote
  type: NodePort
